In [55]:
import numpy as np
import pandas as pd

In [56]:
data=pd.read_csv('zomato.csv',encoding='latin-1')
data.shape

(9551, 21)

In [57]:
data.drop(columns=['Restaurant ID','Is delivering now'],inplace=True)

In [58]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Switch to order menu', 'Price range',
       'Aggregate rating', 'Rating color', 'Rating text', 'Votes'],
      dtype='object')

In [59]:
data['Country Code'].nunique()

15

In [60]:
mask=data['Country Code']==1
data=data[mask]

In [61]:
data['Country Code'].shape

(8652,)

In [62]:
data.drop(columns=['Country Code','Currency'],inplace=True)

In [63]:
data['City'].value_counts()
data.shape

(8652, 17)

In [64]:
mask=data['City'].isin(['New Delhi','Gurgaon','Noida'])
data=data[mask]
data.shape

(7671, 17)

In [65]:
data['Restaurant Name'].value_counts()

Cafe Coffee Day                         81
Domino's Pizza                          75
Subway                                  60
Green Chick Chop                        47
McDonald's                              44
Keventers                               33
Giani                                   28
Baskin Robbins                          26
Barista                                 21
Giani's                                 20
Dunkin' Donuts                          20
Pizza Hut                               20
Costa Coffee                            19
Wah Ji Wah                              19
Pizza Hut Delivery                      19
Chaayos                                 18
Twenty Four Seven                       18
Starbucks                               17
Sagar Ratna                             17
Republic of Chicken                     17
Pind Balluchi                           16
Haldiram's                              15
Aggarwal Sweets                         14
Bikanervala

In [66]:
data.columns

Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [67]:
data.drop(columns=['Restaurant Name','Address', 'Locality', 'Locality Verbose','Rating color','Rating text'],inplace=True)

In [68]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [69]:
data.drop(columns=['Switch to order menu'],inplace=True)

In [70]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [71]:
data['Cuisines'].value_counts()

North Indian                                                                     873
North Indian, Chinese                                                            447
Fast Food                                                                        320
Chinese                                                                          314
North Indian, Mughlai                                                            303
Cafe                                                                             243
Bakery                                                                           200
North Indian, Mughlai, Chinese                                                   181
Bakery, Desserts                                                                 163
Street Food                                                                      144
Pizza, Fast Food                                                                 124
Chinese, Fast Food                                               

In [72]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [73]:
data.head()

City  Longitude   Latitude                       Cuisines  \
1161  Gurgaon  77.039310  28.424831                Cafe, Beverages   
1162  Gurgaon  77.039220  28.424913          North Indian, Mughlai   
1163  Gurgaon  77.097118  28.503077          North Indian, Mughlai   
1164  Gurgaon  77.097185  28.502613  South Indian, Seafood, Kerala   
1165  Gurgaon  77.042009  28.511416                         Bakery   

      Average Cost for two Has Table booking Has Online delivery  Price range  \
1161                   350                No                  No            1   
1162                   800               Yes                 Yes            2   
1163                  2000               Yes                 Yes            4   
1164                  1400               Yes                 Yes            3   
1165                   250                No                  No            1   

      Aggregate rating  Votes  
1161               3.4     16  
1162               2.7     80  
1163               4.3   1887  
1164               4.0    802  
1165               3.0      4

In [74]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7671 entries, 1161 to 9112
Data columns (total 10 columns):
City                    7671 non-null object
Longitude               7671 non-null float64
Latitude                7671 non-null float64
Cuisines                7671 non-null object
Average Cost for two    7671 non-null int64
Has Table booking       7671 non-null object
Has Online delivery     7671 non-null object
Price range             7671 non-null int64
Aggregate rating        7671 non-null float64
Votes                   7671 non-null int64
dtypes: float64(3), int64(3), object(4)
memory usage: 539.4+ KB


In [75]:
data['Has Table booking'].replace('Yes',1,inplace=True)
data['Has Table booking'].replace('No',0,inplace=True)
data['Has Online delivery'].replace('Yes',1,inplace=True)
data['Has Online delivery'].replace('No',0,inplace=True)

In [76]:
data.tail()

City  Longitude   Latitude               Cuisines  \
9108  Noida  77.367524  28.557537  North Indian, Chinese   
9109  Noida  77.367303  28.557929              Fast Food   
9110  Noida  77.367188  28.557842              Fast Food   
9111  Noida  77.367322  28.557930  North Indian, Chinese   
9112  Noida  77.367188  28.557852   Raw Meats, Fast Food   

      Average Cost for two  Has Table booking  Has Online delivery  \
9108                   700                  0                    1   
9109                   400                  0                    0   
9110                   600                  0                    0   
9111                   500                  0                    0   
9112                   250                  0                    0   

      Price range  Aggregate rating  Votes  
9108            2               2.6     34  
9109            1               0.0      1  
9110            2               0.0      3  
9111            2               0.0      0  
9112            1               0.0      1

In [77]:
data.corr()['Average Cost for two']

Longitude               0.071854
Latitude                0.070816
Average Cost for two    1.000000
Has Table booking       0.643845
Has Online delivery     0.072198
Price range             0.848425
Aggregate rating        0.329785
Votes                   0.297741
Name: Average Cost for two, dtype: float64

In [78]:
data.drop(columns=['Longitude','Latitude','Price range','Has Online delivery'],inplace=True)

In [79]:
data

City                                        Cuisines  \
1161  Gurgaon                                 Cafe, Beverages   
1162  Gurgaon                           North Indian, Mughlai   
1163  Gurgaon                           North Indian, Mughlai   
1164  Gurgaon                   South Indian, Seafood, Kerala   
1165  Gurgaon                                          Bakery   
1166  Gurgaon                                       Ice Cream   
1167  Gurgaon                                         Chinese   
1168  Gurgaon                                       Fast Food   
1169  Gurgaon                         Japanese, Thai, Chinese   
1170  Gurgaon                                 Pizza, Desserts   
1171  Gurgaon                            Raw Meats, Fast Food   
1172  Gurgaon                  South Indian, Chinese, Mughlai   
1173  Gurgaon                         Fast Food, North Indian   
1174  Gurgaon                           North Indian, Chinese   
1175  Gurgaon             North Indian, South Indian, Chinese   
1176  Gurgaon                                            Cafe   
1177  Gurgaon                                       Raw Meats   
1178  Gurgaon                            Mithai, North Indian   
1179  Gurgaon                North Indian, Chinese, Fast Food   
1180  Gurgaon                                    North Indian   
1181  Gurgaon                           North Indian, Chinese   
1182  Gurgaon                       South Indian, Street Food   
1183  Gurgaon                           North Indian, Chinese   
1184  Gurgaon                           North Indian, Chinese   
1185  Gurgaon                                    North Indian   
1186  Gurgaon                  North Indian, Mughlai, Seafood   
1187  Gurgaon                                       Fast Food   
1188  Gurgaon                                        Japanese   
1189  Gurgaon              North Indian, Chinese, Continental   
1190  Gurgaon                               Bakery, Fast Food   
...       ...                                             ...   
9083    Noida                                         Italian   
9084    Noida                                            Cafe   
9085    Noida                                       Ice Cream   
9086    Noida                                         Chinese   
9087    Noida                                       Ice Cream   
9088    Noida                               Burger, Fast Food   
9089    Noida                                            Cafe   
9090    Noida                                   Chinese, Thai   
9091    Noida                                       Fast Food   
9092    Noida                                         Chinese   
9093    Noida                           Mughlai, North Indian   
9094    Noida                       Italian, Pizza, Fast Food   
9095    Noida             South Indian, North Indian, Chinese   
9096    Noida                               American, Tex-Mex   
9097    Noida                        North Indian, Rajasthani   
9098    Noida                                       Fast Food   
9099    Noida                                Italian, Chinese   
9100    Noida                                        Desserts   
9101    Noida                             Desserts, Ice Cream   
9102    Noida                                            Cafe   
9103    Noida                  Continental, Lebanese, Mexican   
9104    Noida  Chinese, North Indian, South Indian, Fast Food   
9105    Noida              North Indian, Continental, Chinese   
9106    Noida                           North Indian, Mughlai   
9107    Noida                           North Indian, Chinese   
9108    Noida                           North Indian, Chinese   
9109    Noida                                       Fast Food   
9110    Noida                                       Fast Food   
9111    Noida                           North Indian, Chinese   
9112    Noida                            Raw

In [80]:
cuisine=data.groupby('Cuisines')['Average Cost for two'].mean().reset_index()

In [81]:
new_data=data.merge(cuisine, on='Cuisines')

In [82]:
new_data.drop(columns=['Cuisines'],inplace=True)

In [83]:
new_data.rename(columns={'Average Cost for two_x':'Cost','Average Cost for two_y':'Cuisine'},inplace=True)

In [84]:
new_data=new_data[['City','Has Table booking','Aggregate rating','Votes','Cuisine','Cost']]
new_data

City  Has Table booking  Aggregate rating  Votes      Cuisine  Cost
0       Gurgaon                  0               3.4     16   416.666667   350
1     New Delhi                  0               0.0      0   416.666667   200
2     New Delhi                  0               4.1     92   416.666667   700
3       Gurgaon                  1               2.7     80   755.511551   800
4       Gurgaon                  1               4.3   1887   755.511551  2000
5       Gurgaon                  1               4.0   1595   755.511551  1500
6       Gurgaon                  1               3.8    239   755.511551   700
7       Gurgaon                  0               2.9      5   755.511551   600
8       Gurgaon                  0               3.2     15   755.511551   650
9       Gurgaon                  0               3.3     23   755.511551   600
10      Gurgaon                  0               3.6    213   755.511551   750
11      Gurgaon                  0               4.0     88   755.511551   600
12      Gurgaon                  0               4.1    152   755.511551   650
13      Gurgaon                  0               4.1    229   755.511551  1600
14      Gurgaon                  0               2.6     26   755.511551   800
15      Gurgaon                  1               4.0    111   755.511551  2000
16      Gurgaon                  0               3.6    110   755.511551   900
17      Gurgaon                  0               3.4    260   755.511551   450
18      Gurgaon                  0               3.8    121   755.511551   600
19      Gurgaon                  0               2.7     67   755.511551   800
20      Gurgaon                  0               2.7     11   755.511551   800
21      Gurgaon                  0               3.5     31   755.511551   550
22      Gurgaon                  0               0.0      1   755.511551   400
23      Gurgaon                  1               3.7    340   755.511551  3000
24      Gurgaon                  0               2.8     16   755.511551   700
25      Gurgaon                  1               3.0     61   755.511551   900
26      Gurgaon                  0               0.0      2   755.511551   350
27      Gurgaon                  0               0.0      3   755.511551   500
28      Gurgaon                  0               3.4   1022   755.511551   800
29      Gurgaon                  1               3.3    586   755.511551  1400
...         ...                ...               ...    ...          ...   ...
7641      Noida                  0               0.0      3   500.000000   500
7642      Noida                  0               0.0      2   600.000000   600
7643      Noida                  0               4.1     43   500.000000   500
7644      Noida                  0               3.0      4   500.000000   500
7645      Noida                  0               3.1     10   400.000000   400
7646      Noida                  0               3.2     48   550.000000   550
7647      Noida                  0               3.7    142   600.000000   600
7648      Noida                  0               0.0      2   300.000000   300
7649      Noida                  0               0.0      1   100.000000   100
7650      Noida                  0               0.0      0   500.000000   500
7651      Noida                  0               0.0      2   550.000000   550
7652      Noida                  0               2.9     25   600.000000   600
7653      Noida                  0               3.8    200   500.000000   500
7654      Noida                  0               2.4     77   500.000000   500
7655      Noida                  0               0.0      0   500.000000   500
7656      Noida                  0               2.9      4   400.000000   400
7657      Noida                  0               3.3     12   350.000000   350
7658      Noida                  0               3.1      6   500.000000   500
7659      Noida                  0               0.0      0  

In [85]:
X=new_data.iloc[:,:-1].values
y=new_data.iloc[:,-1].values

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
encoder=LabelEncoder()
X[:,0]=encoder.fit_transform(X[:,0])
X

array([[0, 0, 3.4, 16, 416.6666666666667],
       [1, 0, 0.0, 0, 416.6666666666667],
       [1, 0, 4.1, 92, 416.6666666666667],
       ...,
       [2, 0, 3.5, 105, 450.0],
       [2, 1, 0.0, 0, 1000.0],
       [2, 0, 2.0, 161, 450.0]], dtype=object)

In [88]:
from sklearn.preprocessing import OneHotEncoder

In [89]:
oencoder=OneHotEncoder(categorical_features=[0])
X=oencoder.fit_transform(X).toarray()
X.shape

c:\users\dibyendu das\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\users\dibyendu das\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


(7671, 7)

In [90]:
X=X[:,1:]
X.shape

(7671, 6)

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [172]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)

In [173]:
regressor=LinearRegression()

In [174]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [175]:
y_pred=regressor.predict(X_test)
y_pred

array([ 337.92575309, 2321.77751685,  393.01498215, ..., 1892.52949152,
        314.94517046, 1266.3252991 ])

In [176]:
y_test

array([ 400, 3650,  300, ..., 1600,  400,  400], dtype=int64)

In [177]:
from sklearn.metrics import r2_score

In [178]:
r2_score(y_test,y_pred)

0.718927213860004

In [180]:
from sklearn.ensemble import RandomForestRegressor
forest_regressor=RandomForestRegressor(n_estimators=200)

In [181]:
forest_regressor.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [183]:
y_pred2=forest_regressor.predict(X_test)
y_pred2

array([ 355.52142857, 2990.5       ,  307.83690476, ..., 1619.25      ,
        285.25      , 1010.25      ])

In [186]:
from sklearn.tree import DecisionTreeRegressor
Dec_regressor=DecisionTreeRegressor()

In [187]:
Dec_regressor.fit(X_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [189]:
y_pred3=Dec_regressor.predict(X_test)
y_pred

array([ 337.92575309, 2321.77751685,  393.01498215, ..., 1892.52949152,
        314.94517046, 1266.3252991 ])

In [190]:
from sklearn.svm import SVR

In [191]:
SV_regressor=SVR()
SV_regressor.fit(X_train,y_train)

c:\users\dibyendu das\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
y_pred4=SV_regressor.predict(X_t)